#!/bin/bash

if [[ "$1" = "+" ]]
then
  /usr/local/bin/brightness "$[`/usr/local/bin/brightness`+10]"
elif [[ "$1" = "-" ]]
then
  /usr/local/bin/brightness "$[`/usr/local/bin/brightness`-10]"
else
  echo 'USAGE: $0 +|-'
fi
