#!/usr/bin/env ruby

default_options = '--exclude=node_modules --exclude=.git --exclude=*.jar --exclude=*.js --langmap=Lisp:+.clj'

TAG_FILE = ".tags"
PROJECTS_FILE = ".tagprojects"

projects = (File.exists?(PROJECTS_FILE) ? open(PROJECTS_FILE).lines.map(&:strip) : []) << "*"

# delete the existing TAG_FILE
if (File.exists?(TAG_FILE))
  File.delete(TAG_FILE)
end
create = true

# for each key in the project_config, generate ctags and add them to the tagfile
projects.each do |root|
  project = File.expand_path(root)
  if root == "*" || File.exists?(project)
    puts "Adding tags from '#{project}' to '#{TAG_FILE}'"
    # if this is the first run, then create a new file, else append to an existing one
    create_option = (create ? '' : '-a')
    create = false

    # run ctags
    `ctags #{create_option + ' ' + default_options} -f .tags -R #{project}`
  else
    puts "Couldn't find directory/file '#{project}'"
  end
end
