#!/bin/bash

# gitStatus=$1
gitStatus=`git status 2>/dev/null`

if [[ "$(echo $gitStatus | grep 'nothing to commit')" != "" ]]
then
  color_num='2' # green => clean
elif [[ "$(echo $gitStatus | grep '# Untracked')" != "" ]]
then
  color_num='1' # red => untracked files
else
  color_num='3' # yellow => uncommited changes
fi

echo -n $(tput setaf $color_num)
