#!/bin/bash


iplist=`ifconfig | grep inet | grep netmask | grep broadcast | sed "s/[[:space:]]*inet //" | sed "s/ netmask.*$//"`

for ip in $iplist
do
  if [[ $ip != "127.0.0.1" ]]
  then
    echo $ip
  fi
done
