#!/bin/bash

# kill old versions of this that are running (except this one)
ps -ef | grep `basename $0` | grep -v grep | awk '{print $2}' | grep -v "$$" | xargs kill -9

while [ : ]
do
  cat ~/.password | kinit -l 1h > /home/shicks/.kinit.log
  sleep 1h
done
