#!/bin/bash

# get the ids of current notifications
get_ids() {
  response=$(echo "list" | nc -U /tmp/rofi_notification_daemon)
  echo $response | jq ".[] | .id"
}

# turn the notification ids into an egrep patter
make_pattern() {
  pattern_string='\<('$(get_ids | perl -pe 'chomp if eof' |tr '\n' '|')')\>'
}

make_pattern

WAIT=300

while true; do
  # if not muted
  if [ -f ~/.notifications_mute ] ; then
    sleep $WAIT
  else
    echo checking
    # grep for current ids that are not in the previous pattern string
    new_ids=$(get_ids | egrep -v $pattern_string)
    # update the pattern string
    make_pattern
    if [ "$new_ids" ]; then
      count=$(echo $new_ids | wc -w)
      echo $count new ids
      i3-nagbar -t warning -m "You have $count new notifications" &
    fi
    sleep $WAIT
  fi
done
