#!/bin/bash

# get the ids of current notifications
get_ids() {
  response=$(echo "list" | nc -U /tmp/rofi_notification_daemon)
  echo $response | jq ".[] | .id"
}

# turn the notification ids into an egrep patter
make_pattern() {
  pattern_string='\<('$(get_ids | perl -pe 'chomp if eof' |tr '\n' '|')')\>'
}

make_pattern

while true; do
  echo checking
  # grep for current ids that are not in the previous pattern string
  new_ids=$(get_ids | egrep -v $pattern_string)
  # update the pattern string
  make_pattern
  if [ "$new_ids" ]; then
    count=$(echo $new_ids | wc -w)
    echo $count new ids
    for n in $(seq $count); do
      paplay /usr/share/sounds/ubuntu/notifications/Blip.ogg &
      sleep 1
    done
  fi
  sleep 300
done
