#!/bin/bash

find_procs() {
  ps -ef | grep "$@" | grep -v "$0" | grep -v "grep"
}

if [ "$1" == "-k" ] || [ "$1" == "--kill" ]
then
  shift
  find_procs $@ | awk '{print $2}' | xargs kill -9
else
  find_procs $@
fi

