#!/bin/bash
echo -n 'Password 1: '
read -s password1
echo
echo -n 'Password 2: '
read -s password2
echo
if [[ "$password1" = "$password2" ]]
then
  echo 'Success!'
  exit
else
  echo 'Fail!'
  exit 1
fi
